
clean:
	rm *.*~ *.out makefile~

cleanwin:
	rm *.*~ *.exe a.exe.stackdump makefile~

compile:
	g++ -std=c++14 0527A_Playing_With_Paper.cpp
	./a.out

compwin:
	g++ -std=c++17 1060A_Phone_Numbers.cpp
	./a.exe
