
clean:
	rm *.*~ *.out makefile~

cleanwin:
	rm *.*~ *.exe a.exe.stackdump makefile~

compile:
	g++ -std=c++14 711A_Bus_To_Udayland.cpp
	./a.out

compwin:
	g++ -std=c++17 0149A_Business_Trip.cpp
	./a.exe
